package com.peony.impl.mapper;

import com.peony.api.po.Msglog;
import com.peony.api.vo.search.SearchMsg;

public interface MsglogMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table msglog
	 *
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer uid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table msglog
	 *
	 * @mbggenerated
	 */
	int insert(Msglog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table msglog
	 *
	 * @mbggenerated
	 */
	int insertSelective(Msglog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table msglog
	 *
	 * @mbggenerated
	 */
	Msglog selectByPrimaryKey(Integer uid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table msglog
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Msglog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table msglog
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Msglog record);

	int getCountByCondition(SearchMsg search);
}